[package]
name = "smart_cache_py"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "smart_cache"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { workspace = true, features = ["extension-module"] }
smart_cache_core = { workspace = true }
